apiVersion: v1
kind: Service
metadata:
  labels:
    app: forumkafka
  name: forumkafka-service
spec:
  type: NodePort
  ports:
  - name: "9999"
    port: 9999
    targetPort: 9999
    nodePort: 32005
    protocol: TCP
  selector:
    app: forumkafka
status:
  loadBalancer: {}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: forumkafka-deployment
spec:
  selector:
    matchLabels:
      app: forumkafka
  template:
    metadata:
      labels:
        app: forumkafka
    spec:
      containers:
      - name: forumkafka
        image: volosenkov/forumkafka:v1
        imagePullPolicy: Never
        command: ["java", "-jar", "/usr/local/lib/forumkafka.jar"]
        terminationMessagePath: "/usr/share/1fed8c03-bc30-4889-952e-46f4c19b6ac1.log"
        terminationMessagePolicy: "File"
        ports:
        - containerPort: 9999
          protocol: TCP
      restartPolicy: Always